CREATE Table productreviewsmainml(
    reviewid bigint primary key NOT NULL UNIQUE,
    fivestar double precision,
    fourstar double precision,
    threestar double precision,
    twostar double precision,
    onestar double precision,
    positivesentiment double precision,
    negativeesentiment double precision,
    sadness double precision,
    joy double precision,
    love double precision,
    anger double precision,
    fear double precision,
    surprise double precision,
    admiration double precision,
    amusement double precision,
    anger2 double precision,
    annoyance double precision,
    approval double precision,
    caring double precision,
    confusion double precision,
    curiosity double precision,
    desire double precision,
    disappointment double precision,
    disapproval double precision,
    disgust double precision,
    embarrassment double precision,
    excitement double precision,
    fear2 double precision,
    gratitude double precision,
    grief double precision,
    joy2 double precision,
    love2 double precision,
    nervousness double precision,
    optimism double precision,
    pride double precision,
    realization double precision,
    relief double precision,
    remorse double precision,
    sadness2 double precision,
    surprise2 double precision,
    neutral double precision,
    FOREIGN KEY(reviewid) REFERENCES productreviews(id)

);
alter table productreviewsaddinfoml ADD CONSTRAINT primKeyUnique_productreviewsaddinfoml UNIQUE (reviewid);
CREATE Table productreviewsaddinfoml(
    reviewid bigint primary key UNIQUE,
    fivestar double precision,
    fourstar double precision,
    threestar double precision,
    twostar double precision,
    onestar double precision,
    positivesentiment double precision,
    negativeesentiment double precision,
    sadness double precision,
    joy double precision,
    love double precision,
    anger double precision,
    fear double precision,
    surprise double precision,
    admiration double precision,
    amusement double precision,
    anger2 double precision,
    annoyance double precision,
    approval double precision,
    caring double precision,
    confusion double precision,
    curiosity double precision,
    desire double precision,
    disappointment double precision,
    disapproval double precision,
    disgust double precision,
    embarrassment double precision,
    excitement double precision,
    fear2 double precision,
    gratitude double precision,
    grief double precision,
    joy2 double precision,
    love2 double precision,
    nervousness double precision,
    optimism double precision,
    pride double precision,
    realization double precision,
    relief double precision,
    remorse double precision,
    sadness2 double precision,
    surprise2 double precision,
    neutral double precision,
    FOREIGN KEY(reviewid) REFERENCES productreviews(id)

)

